k8s:
    user_password: ENC[AES256_GCM,data:VuW9Eeq7O4oYZKjPEGJNxjXErqFk,iv:aTnaVOHcNNAilEORKdMe7RwQnxCBtdmtDZBPoZHnNMI=,tag:6HSH1WmjcDIpqJjvlHYQtA==,type:str]
    ssh_key: ENC[AES256_GCM,data:XAKGOhm+m05UH08VwCk2azK64v8D3uImaHim5AnHoFBC8OJLOTU9oxWjdWWEn0WfOZ4ZEb6W0stWSy69aHNL1kOrn5IRnx/L1Cua69A3l+poXB+6m/3Va56LbE5Y1SOy9AIaQCm2W+hRENZ/xnqWykey4vqlB61deUZ3eSV/2wORSIEU4uT27qccfTTHRn4pyKOITJj/5kIa3ccyMLcwW9jevJwcn8AGpIg9emkBTPzQSnZtUubviEFaIrUtE/moZdEssDVJl5HZ4Ba0A1gHiSPy5uaiCwN4QxHtWAopI33IVnfF8arzaY2SaIhJUBQfN2ZSpxAoEsGqoGybnHUPPzR80yuJPxah1cXi9sBjhe8OVh2JFfCY5BLHNEvO5rzJ/yr6V46gCVIvqKj6mV3N05ua0vgiwDhFzZxlb9+YzxGOX2Xp8XgsZJ6xOXwix3SsgmhGl9sun/9Udx04kbkC07SegeBnb0lC4juiMlfVv0pGVjRaa1gjcMLAm20H/sQbnB7Z9e8CYJMtiZHp+tXS8ffaHrip,iv:6RxK0S0z35jn1Ow7qut1mA52fTLgIYQG0rIeFhwGBMY=,tag:zmdbtysJUiPKSeGd7n5pDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdapdgc8jy47q354dmp9988fpl26xfvjknglp3r7ska0q8wpcsgq8vd96v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZKzAyMEtIVGlTWTRjMCtN
            bzBJT2xpT0k4T3B6QjZwWHVaeW9GM1RmVVU4ClFZcVVoZkFpd1ljek1YQUEzdFhl
            MjBVUjllNnc4ZGNLZWNDcW1IOHdRcVUKLS0tIG1qWVF1Tm00S1NlOEVLMU4vTllH
            QVEwZktHNjdnYXp6NTNPY3Q0d2l6QUUKXk4U7mdSFIbxr5zI4RDqSIy1MmWbtFj9
            HWSnxIjrdydoy5TgTTaeQAOSOXmmUw77/tZduycIqFkCGNV67phjCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-01T07:19:44Z"
    mac: ENC[AES256_GCM,data:CafQDL9U2mg8KQvmISJSsyMHud1iOvhXr+QTHfUaF+B3uDmUAfhBwo6HGsfue1Z0m5J/TB77zdUroO43LtzbuI6b2dOVtBP6eFfL0fWpK3khnnhh4Oh4kLHeHpBSgMdOwY/fUF2rtPOwtRKXDMhdARkv7890az0W+o6hPbHH69E=,iv:pJzVcnXvR0YIaew4QQNg2vCbdaZKOf2kNibIwLEUiJg=,tag:FsX6SwJ9BEP8TbkeswxUyw==,type:str]
    pgp: []
    encrypted_regex: ^(k8s)$
    version: 3.7.1
